// DEMO MODE — clearly-labelled sample stories for offline design evaluation.
// Every title is prefixed "SAMPLE:" and the UI adds an amber DEMO badge.
// Never mixed with live data: the toggle swaps the corpus wholesale.
import type { NewsItem } from "./types";

const now = Date.now();
const h = 3_600_000;

const D = (
  id: string,
  hoursAgo: number,
  title: string,
  source: string,
  category: NewsItem["category"],
  tickers: string[],
  sectors: string[],
  sentiment: NewsItem["sentiment"],
  impactScore: NewsItem["impactScore"],
  whyItMatters: string,
  extra: Partial<NewsItem> = {},
): NewsItem => ({
  id,
  title: `SAMPLE: ${title}`,
  url: "https://example.com/demo",
  source,
  sourceDomain: "example.com",
  publishedAt: now - hoursAgo * h,
  fetchedAt: now,
  category,
  sentiment,
  impactScore,
  tickers,
  sectors,
  assetImpact: {
    equity: category !== "gold-commodities",
    gold: category === "gold-commodities",
    inr: category === "macro-policy",
    bonds: category === "macro-policy",
  },
  whyItMatters,
  duplicateCount: 0,
  isSpeculation: false,
  demo: true,
  ...extra,
});

export const DEMO_STORIES: NewsItem[] = [
  D("d1", 0.4, "HAL bags ₹2,450 cr avionics contract from Ministry of Defence", "Demo Wire", "tenders-contracts", ["HAL"], ["defence"], "bullish", 5,
    "Order inflow of ~₹2,450 cr — directly accretive to HAL's order book and revenue visibility.",
    { orderValueCr: 2450, awardingBody: "Ministry Of Defence" }),
  D("d2", 0.9, "RBI holds repo rate, shifts stance to neutral; banks rally", "Demo Wire", "macro-policy", ["SBIN", "HDFCBANK"], ["banking"], "bullish", 5,
    "Policy signal with read-through to rates, liquidity and sector earnings — moves index heavyweights and rate-sensitives.",
    { assetImpact: { equity: true, gold: false, inr: true, bonds: true } }),
  D("d3", 1.3, "Gold hits record as Fed cut bets rise; import duty cut stokes India demand", "Demo Wire", "gold-commodities", ["TITAN"], ["consumer"], "bullish", 4,
    "Tracks the gold complex — bullion prices, import duty and INR feed straight into jewellers, MCX and gold-loan NBFCs.",
    { assetImpact: { equity: false, gold: true, inr: true, bonds: false } }),
  D("d4", 1.8, "RVNL emerges L1 bidder for ₹1,180 cr rail electrification work order", "Demo Wire", "tenders-contracts", ["RVNL"], ["railways"], "bullish", 4,
    "Government/PSU order flow linked to RVNL — order-driven names tend to re-rate on award confirmation.",
    { orderValueCr: 1180, awardingBody: "Indian Railways" }),
  D("d5", 2.2, "Electoral bond data shows large contributions by infra majors, opposition flags quid-pro-quo", "Demo Wire", "stocks-corporate", ["ADANIENT"], ["infra"], "neutral", 3,
    "Public reporting on political-proximity / funding disclosures. Alignment pattern only — no wrongdoing is implied.",
    { isSpeculation: true }),
  D("d6", 2.6, "Cabinet approves PLI expansion for electronics; Dixon-style EMS names in focus", "Demo Wire", "macro-policy", [], ["capital-goods"], "bullish", 4,
    "Policy/incentive announcement with read-through to the EMS segment.",
    { assetImpact: { equity: true, gold: false, inr: false, bonds: false } }),
  D("d7", 3.1, "Adani Ports wins concession for new container terminal at state-run port", "Demo Wire", "tenders-contracts", ["ADANIPORTS"], ["infra"], "bullish", 4,
    "Reported asset-transfer / concession development — watch capacity and margin guidance.",
    { isSpeculation: true }),
  D("d8", 3.7, "Vodafone Idea gets ₹14,000 cr lifeline from SBI-led consortium, reports say", "Demo Wire", "stocks-corporate", ["VODAFONEIDEA", "SBIN"], ["telecom", "banking"], "neutral", 4,
    "Reported state-linked financing / institutional exposure."),
  D("d9", 4.4, "SBI IPO of subsidiary to open next week; price band expected Thursday", "Demo Wire", "ipo", ["SBIN"], ["banking"], "neutral", 2,
    "Primary-market action — subscription and listing signals for the issue."),
  D("d10", 5.0, "Wall Street slides as US CPI runs hot; GIFT Nifty signals weak open", "Demo Wire", "global-cues", [], [], "bearish", 3,
    "Overnight global cue — sets the GIFT Nifty / opening tone and FII risk appetite for Indian equities.",
    { assetImpact: { equity: true, gold: true, inr: true, bonds: true } }),
  D("d11", 6.2, "ED raids premises linked to midcap realty group; shares plunge 12%", "Demo Wire", "stocks-corporate", ["DLF"], ["realty"], "bearish", 4,
    "Negative trigger for DLF — watch for follow-through selling and analyst revisions."),
  D("d12", 7.5, "Government defends airport award process amid controversy over clearances", "Demo Wire", "geopolitics", ["ADANIENT"], ["infra"], "neutral", 3,
    "Reported narrative-asymmetry signal (defence/exclusion pattern in public statements).",
    { isSpeculation: true }),
  D("d13", 9.0, "BEL secures ₹920 cr radar supply order from defence ministry", "Demo Wire", "tenders-contracts", ["BEL"], ["defence"], "bullish", 4,
    "Order inflow of ~₹920 cr — directly accretive to BEL's order book and revenue visibility.",
    { orderValueCr: 920, awardingBody: "Ministry Of Defence" }),
  D("d14", 26.0, "NTPC signs MoU with ministry for 5 GW solar EPC push", "Demo Wire", "tenders-contracts", ["NTPC"], ["power"], "bullish", 3,
    "Government/PSU order flow linked to NTPC — order-driven names tend to re-rate on award confirmation.",
    { orderValueCr: 6100, awardingBody: "Ministry Of Power" }),
  D("d15", 30.0, "Record fast-track clearance granted for new Mundra SEZ expansion, officials say", "Demo Wire", "stocks-corporate", ["ADANIPORTS"], ["infra"], "bullish", 3,
    "Reported clearance/approval development.",
    { isSpeculation: true }),
  D("d16", 50.0, "LIC raises stake in engineering major to 7.2% via open market buys", "Demo Wire", "stocks-corporate", ["LT"], ["infra"], "neutral", 2,
    "Reported state-linked financing / institutional exposure."),
];
