// Entity dictionary: aliases → NSE ticker + sector + PSU flag.
// Extendable — add entries here and the classifier + Chanakya engine pick them up.
import type { EntityDef } from "./types";

const E = (
  ticker: string,
  name: string,
  sector: string,
  aliases: string[],
  isPSU = false,
  group?: string,
): EntityDef => ({ ticker, name, sector, aliases, isPSU, group });

export const ENTITIES: EntityDef[] = [
  // ---- Nifty 50 core ----
  E("RELIANCE", "Reliance Industries", "energy", ["reliance industries", "ril", "jio platforms", "reliance jio"], false, "Reliance"),
  E("TCS", "Tata Consultancy Services", "it", ["tcs", "tata consultancy"], false, "Tata"),
  E("HDFCBANK", "HDFC Bank", "banking", ["hdfc bank"]),
  E("ICICIBANK", "ICICI Bank", "banking", ["icici bank"]),
  E("INFY", "Infosys", "it", ["infosys", "infy"]),
  E("HINDUNILVR", "Hindustan Unilever", "fmcg", ["hindustan unilever", "hul"]),
  E("ITC", "ITC", "fmcg", ["itc ltd", "itc"]),
  E("SBIN", "State Bank of India", "banking", ["state bank of india", "sbi"], true),
  E("BHARTIARTL", "Bharti Airtel", "telecom", ["bharti airtel", "airtel"]),
  E("KOTAKBANK", "Kotak Mahindra Bank", "banking", ["kotak mahindra", "kotak bank"]),
  E("LT", "Larsen & Toubro", "infra", ["larsen", "l&t", "larsen & toubro", "larsen and toubro"], false, "L&T"),
  E("AXISBANK", "Axis Bank", "banking", ["axis bank"]),
  E("ASIANPAINT", "Asian Paints", "consumer", ["asian paints"]),
  E("MARUTI", "Maruti Suzuki", "auto", ["maruti suzuki", "maruti"]),
  E("SUNPHARMA", "Sun Pharmaceutical", "pharma", ["sun pharma", "sun pharmaceutical"]),
  E("TITAN", "Titan Company", "consumer", ["titan company", "titan"], false, "Tata"),
  E("ULTRACEMCO", "UltraTech Cement", "cement", ["ultratech", "ultratech cement"], false, "Birla"),
  E("BAJFINANCE", "Bajaj Finance", "nbfc", ["bajaj finance"], false, "Bajaj"),
  E("NESTLEIND", "Nestlé India", "fmcg", ["nestle india", "nestlé india"]),
  E("WIPRO", "Wipro", "it", ["wipro"]),
  E("M&M", "Mahindra & Mahindra", "auto", ["mahindra & mahindra", "mahindra and mahindra", "m&m"], false, "Mahindra"),
  E("NTPC", "NTPC", "power", ["ntpc"], true),
  E("HCLTECH", "HCL Technologies", "it", ["hcl tech", "hcl technologies"]),
  E("POWERGRID", "Power Grid Corp", "power", ["power grid", "powergrid"], true),
  E("TATAMOTORS", "Tata Motors", "auto", ["tata motors"], false, "Tata"),
  E("TATASTEEL", "Tata Steel", "metals", ["tata steel"], false, "Tata"),
  E("ONGC", "Oil & Natural Gas Corp", "energy", ["ongc", "oil and natural gas"], true),
  E("ADANIENT", "Adani Enterprises", "infra", ["adani enterprises"], false, "Adani"),
  E("ADANIPORTS", "Adani Ports & SEZ", "infra", ["adani ports", "apsez", "mundra port"], false, "Adani"),
  E("COALINDIA", "Coal India", "mining", ["coal india"], true),
  E("HINDZINC", "Hindustan Zinc", "metals", ["hindustan zinc"], false, "Vedanta"),
  E("BAJAJAUTO", "Bajaj Auto", "auto", ["bajaj auto"], false, "Bajaj"),
  E("INDUSINDBK", "IndusInd Bank", "banking", ["indusind"]),
  E("TECHM", "Tech Mahindra", "it", ["tech mahindra"], false, "Mahindra"),
  E("JSWSTEEL", "JSW Steel", "metals", ["jsw steel"], false, "JSW"),
  E("GRASIM", "Grasim Industries", "cement", ["grasim"], false, "Birla"),
  E("CIPLA", "Cipla", "pharma", ["cipla"]),
  E("DRREDDY", "Dr Reddy's", "pharma", ["dr reddy", "dr. reddy"]),
  E("EICHERMOT", "Eicher Motors", "auto", ["eicher", "royal enfield"]),
  E("APOLLOHOSP", "Apollo Hospitals", "healthcare", ["apollo hospitals"]),
  E("BRITANNIA", "Britannia", "fmcg", ["britannia"]),
  E("TATACONSUM", "Tata Consumer", "fmcg", ["tata consumer"], false, "Tata"),
  E("HEROMOTOCO", "Hero MotoCorp", "auto", ["hero motocorp", "hero moto"]),
  E("SBILIFE", "SBI Life", "insurance", ["sbi life"]),
  E("HDFCLIFE", "HDFC Life", "insurance", ["hdfc life"]),
  E("BPCL", "Bharat Petroleum", "energy", ["bpcl", "bharat petroleum"], true),
  E("HINDALCO", "Hindalco", "metals", ["hindalco"], false, "Birla"),
  E("DIVISLAB", "Divi's Laboratories", "pharma", ["divi's", "divis"]),
  E("LTIM", "LTIMindtree", "it", ["ltimindtree", "lti mindtree"], false, "L&T"),
  E("TRENT", "Trent", "retail", ["trent", "westside", "zudio"], false, "Tata"),
  E("BEL", "Bharat Electronics", "defence", ["bharat electronics", "bel ltd"], true),
  E("JIOFIN", "Jio Financial", "nbfc", ["jio financial"], false, "Reliance"),
  E("SHRIRAMFIN", "Shriram Finance", "nbfc", ["shriram finance"]),
  E("VEDL", "Vedanta", "metals", ["vedanta"], false, "Vedanta"),
  E("ZOMATO", "Zomato (Eternal)", "consumer-tech", ["zomato", "eternal ltd", "blinkit"]),
  // ---- Adani group ----
  E("ADANIGREEN", "Adani Green Energy", "power", ["adani green"], false, "Adani"),
  E("ADANIPOWER", "Adani Power", "power", ["adani power"], false, "Adani"),
  E("ADANITRANS", "Adani Energy Solutions", "power", ["adani transmission", "adani energy solutions"], false, "Adani"),
  E("ADANIWILMAR", "Adani Wilmar", "fmcg", ["adani wilmar"], false, "Adani"),
  E("ACC", "ACC Cement", "cement", ["acc cement", "acc ltd"], false, "Adani"),
  E("AMBUJACEM", "Ambuja Cements", "cement", ["ambuja"], false, "Adani"),
  E("NDTV", "NDTV", "media", ["ndtv"], false, "Adani"),
  // ---- Defence PSU (order-flow sensitive) ----
  E("HAL", "Hindustan Aeronautics", "defence", ["hindustan aeronautics", "hal"], true),
  E("BDL", "Bharat Dynamics", "defence", ["bharat dynamics", "bdl"], true),
  E("MAZDOCK", "Mazagon Dock", "defence", ["mazagon dock", "mdl"], true),
  E("GRSE", "Garden Reach Shipbuilders", "defence", ["garden reach", "grse"], true),
  E("COCHINSHIP", "Cochin Shipyard", "defence", ["cochin shipyard"], true),
  E("MIDHANI", "Mishra Dhatu Nigam", "defence", ["midhani", "mishra dhatu"], true),
  E("BEML", "BEML", "defence", ["beml"], true),
  E("DATAPATTNS", "Data Patterns", "defence", ["data patterns"]),
  E("SOLARINDS", "Solar Industries", "defence", ["solar industries"]),
  E("BHEL", "Bharat Heavy Electricals", "capital-goods", ["bhel", "bharat heavy electricals"], true),
  // ---- Rail PSU ----
  E("RVNL", "Rail Vikas Nigam", "railways", ["rvnl", "rail vikas"], true),
  E("IRFC", "Indian Railway Finance Corp", "railways", ["irfc", "indian railway finance"], true),
  E("IRCON", "Ircon International", "railways", ["ircon"], true),
  E("RAILTEL", "RailTel", "railways", ["railtel"], true),
  E("RITES", "RITES", "railways", ["rites ltd", "rites"], true),
  E("TITAGARH", "Titagarh Rail Systems", "railways", ["titagarh"]),
  E("TEXRAIL", "Texmaco Rail", "railways", ["texmaco"]),
  E("IRCTC", "IRCTC", "railways", ["irctc"], true),
  E("JUPITERWAG", "Jupiter Wagons", "railways", ["jupiter wagons"]),
  // ---- Power / infra PSU ----
  E("NBCC", "NBCC (India)", "infra", ["nbcc"], true),
  E("HUDCO", "HUDCO", "nbfc", ["hudco"], true),
  E("NHPC", "NHPC", "power", ["nhpc"], true),
  E("SJVN", "SJVN", "power", ["sjvn"], true),
  E("RECLTD", "REC", "nbfc", ["rec ltd", "rec limited"], true),
  E("PFC", "Power Finance Corp", "nbfc", ["pfc", "power finance"], true),
  E("IREDA", "IREDA", "nbfc", ["ireda", "indian renewable energy development"], true),
  E("NHAI", "NHAI", "infra", ["nhai", "national highways authority"], true),
  // ---- Energy PSU ----
  E("OIL", "Oil India", "energy", ["oil india"], true),
  E("GAIL", "GAIL (India)", "energy", ["gail"], true),
  E("IOC", "Indian Oil", "energy", ["indian oil", "iocl"], true),
  E("HPCL", "Hindustan Petroleum", "energy", ["hpcl", "hindustan petroleum"], true),
  E("PETRONET", "Petronet LNG", "energy", ["petronet"]),
  // ---- PSU banks / insurers ----
  E("PNB", "Punjab National Bank", "banking", ["punjab national bank", "pnb"], true),
  E("BANKBARODA", "Bank of Baroda", "banking", ["bank of baroda", "bob"], true),
  E("CANBK", "Canara Bank", "banking", ["canara bank"], true),
  E("UNIONBANK", "Union Bank of India", "banking", ["union bank"], true),
  E("LIC", "Life Insurance Corp", "insurance", ["lic", "life insurance corporation"], true),
  // ---- Others frequently in order news ----
  E("KEC", "KEC International", "infra", ["kec international"]),
  E("KALPATARU", "Kalpataru Projects", "infra", ["kalpataru projects", "kalpataru power"]),
  E("CUMMINSIND", "Cummins India", "capital-goods", ["cummins india"]),
  E("SIEMENS", "Siemens India", "capital-goods", ["siemens india", "siemens"]),
  E("ABB", "ABB India", "capital-goods", ["abb india", "abb"]),
  E("GE Vernova T&D India", "capital-goods", "capital-goods", ["ge t&d india"]),
  E("CGPOWER", "CG Power", "capital-goods", ["cg power", "crompton greaves power"]),
  E("ASTRAL", "Astral", "building-materials", ["astral"]),
  E("DMART", "Avenue Supermarts", "retail", ["dmart", "avenue supermarts"]),
  E("PAYTM", "One97 (Paytm)", "fintech", ["paytm", "one97", "one 97"]),
  E("NYKAA", "Nykaa", "consumer-tech", ["nykaa"]),
  E("POLICYBZR", "PB Fintech", "fintech", ["policybazaar", "pb fintech"]),
  E("DELHIVERY", "Delhivery", "logistics", ["delhivery"]),
  E("INDIGO", "InterGlobe Aviation", "aviation", ["indigo", "interglobe aviation"]),
  E("VODAFONEIDEA", "Vodafone Idea", "telecom", ["vodafone idea", "vi "]),
  E("YESBANK", "Yes Bank", "banking", ["yes bank"]),
  E("IDFCFIRSTB", "IDFC First Bank", "banking", ["idfc first"]),
  E("AUBANK", "AU Small Finance Bank", "banking", ["au small finance"]),
  E("BANDHANBNK", "Bandhan Bank", "banking", ["bandhan"]),
  E("MOTHERSON", "Samvardhana Motherson", "auto-ancillary", ["motherson", "samvardhana"]),
  E("TATAPOWER", "Tata Power", "power", ["tata power"], false, "Tata"),
  E("ADANIGREEN", "Adani Green", "power", ["adani green energy"], false, "Adani"),
  E("JSWENERGY", "JSW Energy", "power", ["jsw energy"], false, "JSW"),
  E("TORNTPOWER", "Torrent Power", "power", ["torrent power"]),
  E("DLF", "DLF", "realty", ["dlf"]),
  E("LODHA", "Macrotech (Lodha)", "realty", ["lodha", "macrotech"]),
  E("GODREJPROP", "Godrej Properties", "realty", ["godrej properties"]),
  E("OBEROIRLTY", "Oberoi Realty", "realty", ["oberoi realty"]),
  E("PIIND", "PI Industries", "chemicals", ["pi industries"]),
  E("SRF", "SRF", "chemicals", ["srf ltd"]),
  E("PIDILITIND", "Pidilite", "chemicals", ["pidilite"]),
  E("NAUKRI", "Info Edge", "consumer-tech", ["info edge", "naukri"]),
  E("MANKIND", "Mankind Pharma", "pharma", ["mankind"]),
  E("AUROPHARMA", "Aurobindo Pharma", "pharma", ["aurobindo"]),
  E("LUPIN", "Lupin", "pharma", ["lupin"]),
  E("ZYDUSLIFE", "Zydus Lifesciences", "pharma", ["zydus"]),
  E("TORNTPHARM", "Torrent Pharma", "pharma", ["torrent pharma"]),
  E("MAXHEALTH", "Max Healthcare", "healthcare", ["max healthcare"]),
  E("FORTIS", "Fortis Healthcare", "healthcare", ["fortis"]),
];

// Longest-alias-first so "adani enterprises" beats "adani"
export const ALIAS_INDEX: { alias: string; entity: EntityDef }[] = ENTITIES.flatMap((e) =>
  [e.name.toLowerCase(), e.ticker.toLowerCase(), ...e.aliases.map((a) => a.toLowerCase())].map((alias) => ({
    alias,
    entity: e,
  })),
).sort((a, b) => b.alias.length - a.alias.length);

export const SECTORS = [
  "defence",
  "railways",
  "infra",
  "power",
  "banking",
  "nbfc",
  "it",
  "pharma",
  "auto",
  "fmcg",
  "metals",
  "cement",
  "realty",
  "telecom",
  "energy",
  "chemicals",
  "consumer-tech",
  "capital-goods",
] as const;

export const MINISTRIES = [
  "ministry of defence",
  "ministry of railways",
  "ministry of finance",
  "ministry of road transport",
  "nhai",
  "ministry of power",
  "ministry of coal",
  "ministry of petroleum",
  "ministry of housing",
  "ministry of electronics",
  "meity",
  "department of space",
  "isro",
  "coal india",
  "ntpc",
  "indian railways",
  "dgca",
  "sebi",
  "rbi",
];
